# Generated by Django 4.2.6 on 2023-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
