# Generated by Django 4.2.6 on 2023-11-01 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='income',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
